name: Deploy pages

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Source Han Sans SC + Mono + Emoji
        run: |
          # 1. 思源黑体（Sans）
          wget -q https://github.com/adobe-fonts/source-han-sans/releases/download/2.004R/SourceHanSansSC.zip
          unzip -q SourceHanSansSC.zip -d sans
          sudo mkdir -p /usr/share/fonts/opentype/source-han-sans
          sudo cp sans/SubsetOTF/SC/*.otf /usr/share/fonts/opentype/source-han-sans/

          # 2. 思源等宽 (Source Han Mono)
          wget -q https://github.com/adobe-fonts/source-han-mono/releases/download/1.002R/SourceHanMonoSC.zip
          unzip -q SourceHanMonoSC.zip -d mono

          sudo mkdir -p /usr/share/fonts/opentype/source-han-mono
          sudo cp mono/SubsetOTF/SC/*.otf /usr/share/fonts/opentype/source-han-mono/

          # 3. Emoji（Google Noto Color Emoji）
          sudo apt-get update -y
          sudo apt-get install -y fonts-noto-color-emoji

          # 4. 刷新缓存
          sudo fc-cache -fv

          # 5. 验证
          fc-list :lang=zh | grep -i source
          fc-list | grep -i emoji

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        working-directory: slides
        run: npm i -g @antfu/ni

      - name: Install dependencies
        working-directory: slides
        run: nci

      - name: Build
        working-directory: slides
        run: nr build --base /${{github.event.repository.name}}/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: slides/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build

    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
