name: Deploy pages

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install all CJK & Emoji fonts via apt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            fonts-noto-cjk \
            fonts-noto-cjk-extra \
            fonts-noto-color-emoji
          sudo fc-cache -fv

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        working-directory: slides
        run: npm i -g @antfu/ni

      - name: Install dependencies
        working-directory: slides
        run: nci

      - name: Build
        working-directory: slides
        run: nr build --base /${{github.event.repository.name}}/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: slides/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build

    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
